name: Deploy Docker Image to Azure Web App

env:
  AZURE_WEBAPP_NAME: dota2webapp
  DOCKER_IMAGE: nicwa05/dota2webapp:latest 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: dota2webapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: nicwa05/dota2webapp:latest

